import type { SDLDocument } from '../types';
import type { GeneratorResult, GeneratedFile } from './types';

/**
 * Generates monitoring and observability configs.
 * Includes Prometheus alerting rules, Grafana dashboard, and prometheus.yml scrape config.
 * Derived from SDL NFRs (availability target, response time, scaling).
 * Deterministic — same input always produces identical output.
 */
export function generateMonitoring(doc: SDLDocument): GeneratorResult {
  const files: GeneratedFile[] = [];
  const backends = doc.architecture.projects.backend || [];
  const frontends = doc.architecture.projects.frontend || [];

  files.push({
    path: 'artifacts/monitoring/prometheus.yml',
    content: renderPrometheusConfig(doc, backends),
  });

  files.push({
    path: 'artifacts/monitoring/alert-rules.yml',
    content: renderAlertRules(doc, backends),
  });

  files.push({
    path: 'artifacts/monitoring/grafana-dashboard.json',
    content: renderGrafanaDashboard(doc, backends, frontends),
  });

  return {
    artifactType: 'deployment-guide',
    files,
    metadata: {
      solutionName: doc.solution.name,
      availabilityTarget: doc.nonFunctional.availability.target,
      hasApiResponseTimeTarget: !!doc.nonFunctional.performance?.apiResponseTime,
      serviceCount: backends.length + frontends.length,
      monitoringProvider: doc.integrations?.monitoring?.provider || 'prometheus',
    },
  };
}

// ─── Helpers ───

function slugify(s: string): string {
  return s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
}

function parseResponseTimeMs(target: string | undefined): number {
  if (!target) return 500;
  const match = target.match(/<?\s*(\d+)/);
  return match ? parseInt(match[1], 10) : 500;
}

function getErrorBudgetPercent(availability: string): number {
  const avail = parseFloat(availability);
  return Math.round((100 - avail) * 100) / 100;
}

// ─── Prometheus Config ───

function renderPrometheusConfig(doc: SDLDocument, backends: { name: string; framework: string }[]): string {
  const lines: string[] = [];
  lines.push(`# Prometheus configuration — ${doc.solution.name}`);
  lines.push(`# Generated by arch0 SDL`);
  lines.push('');
  lines.push('global:');
  lines.push('  scrape_interval: 15s');
  lines.push('  evaluation_interval: 15s');
  lines.push('');
  lines.push('rule_files:');
  lines.push('  - "alert-rules.yml"');
  lines.push('');
  lines.push('scrape_configs:');

  // Prometheus self-monitoring
  lines.push('  - job_name: "prometheus"');
  lines.push('    static_configs:');
  lines.push('      - targets: ["localhost:9090"]');

  // Backend services
  for (const be of backends) {
    const name = slugify(be.name);
    const port = getBackendPort(be.framework);
    lines.push('');
    lines.push(`  - job_name: "${name}"`);
    lines.push(`    metrics_path: /metrics`);
    lines.push('    static_configs:');
    lines.push(`      - targets: ["${name}:${port}"]`);
    lines.push(`        labels:`);
    lines.push(`          service: "${name}"`);
    lines.push(`          framework: "${be.framework}"`);
  }

  // Node exporter
  lines.push('');
  lines.push('  - job_name: "node-exporter"');
  lines.push('    static_configs:');
  lines.push('      - targets: ["node-exporter:9100"]');

  return lines.join('\n') + '\n';
}

function getBackendPort(framework: string): number {
  switch (framework) {
    case 'python-fastapi': return 8000;
    case 'go': return 8080;
    case 'dotnet-8': return 5000;
    case 'java-spring': return 8080;
    case 'ruby-rails': return 3000;
    case 'php-laravel': return 9000;
    default: return 3000;
  }
}

// ─── Alert Rules ───

function renderAlertRules(doc: SDLDocument, backends: { name: string }[]): string {
  const lines: string[] = [];
  const availTarget = doc.nonFunctional.availability.target;
  const errorBudget = getErrorBudgetPercent(availTarget);
  const responseTimeMs = parseResponseTimeMs(doc.nonFunctional.performance?.apiResponseTime);

  lines.push(`# Prometheus alerting rules — ${doc.solution.name}`);
  lines.push(`# Availability target: ${availTarget}% (error budget: ${errorBudget}%)`);
  lines.push('');
  lines.push('groups:');
  lines.push(`  - name: ${slugify(doc.solution.name)}-alerts`);
  lines.push('    rules:');

  // High error rate alert (derived from availability target)
  const errorThreshold = errorBudget > 1 ? 5 : errorBudget > 0.1 ? 1 : 0.1;
  lines.push('');
  lines.push('      # Error rate exceeds error budget');
  lines.push('      - alert: HighErrorRate');
  lines.push(`        expr: sum(rate(http_requests_total{status=~"5.."}[5m])) / sum(rate(http_requests_total[5m])) > ${errorThreshold / 100}`);
  lines.push('        for: 5m');
  lines.push('        labels:');
  lines.push('          severity: critical');
  lines.push('        annotations:');
  lines.push(`          summary: "Error rate exceeds ${errorThreshold}%"`);
  lines.push(`          description: "HTTP 5xx error rate is above ${errorThreshold}% for 5 minutes (availability target: ${availTarget}%)"`);

  // High latency alert (derived from performance target)
  lines.push('');
  lines.push('      # API response time exceeds target');
  lines.push('      - alert: HighLatency');
  lines.push(`        expr: histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (le)) > ${responseTimeMs / 1000}`);
  lines.push('        for: 5m');
  lines.push('        labels:');
  lines.push('          severity: warning');
  lines.push('        annotations:');
  lines.push(`          summary: "P95 latency exceeds ${responseTimeMs}ms"`);
  lines.push(`          description: "P95 API response time is above ${responseTimeMs}ms for 5 minutes"`);

  // Service down alerts per backend
  for (const be of backends) {
    const name = slugify(be.name);
    lines.push('');
    lines.push(`      # Service ${name} is down`);
    lines.push(`      - alert: ServiceDown_${name.replace(/-/g, '_')}`);
    lines.push(`        expr: up{job="${name}"} == 0`);
    lines.push('        for: 1m');
    lines.push('        labels:');
    lines.push('          severity: critical');
    lines.push('        annotations:');
    lines.push(`          summary: "${name} is down"`);
    lines.push(`          description: "Service ${name} has been unreachable for 1 minute"`);
  }

  // High CPU usage
  lines.push('');
  lines.push('      # High CPU usage');
  lines.push('      - alert: HighCpuUsage');
  lines.push('        expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 85');
  lines.push('        for: 10m');
  lines.push('        labels:');
  lines.push('          severity: warning');
  lines.push('        annotations:');
  lines.push('          summary: "CPU usage above 85%"');
  lines.push('          description: "CPU usage has been above 85% for 10 minutes"');

  // High memory usage
  lines.push('');
  lines.push('      # High memory usage');
  lines.push('      - alert: HighMemoryUsage');
  lines.push('        expr: (1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) > 0.9');
  lines.push('        for: 5m');
  lines.push('        labels:');
  lines.push('          severity: warning');
  lines.push('        annotations:');
  lines.push('          summary: "Memory usage above 90%"');
  lines.push('          description: "Memory usage has been above 90% for 5 minutes"');

  // Database connection pool alert
  const dbType = doc.data.primaryDatabase.type;
  if (['postgres', 'mysql', 'sqlserver'].includes(dbType)) {
    lines.push('');
    lines.push('      # Database connection pool exhaustion');
    lines.push('      - alert: DatabaseConnectionPoolHigh');
    lines.push('        expr: db_pool_active_connections / db_pool_max_connections > 0.8');
    lines.push('        for: 5m');
    lines.push('        labels:');
    lines.push('          severity: warning');
    lines.push('        annotations:');
    lines.push('          summary: "Database connection pool above 80%"');
    lines.push('          description: "Connection pool utilization is above 80% for 5 minutes"');
  }

  return lines.join('\n') + '\n';
}

// ─── Grafana Dashboard ───

function renderGrafanaDashboard(
  doc: SDLDocument,
  backends: { name: string; framework: string }[],
  frontends: { name: string }[],
): string {
  const panels: object[] = [];
  let nextId = 1;
  let yPos = 0;

  // Request rate panel
  panels.push({
    id: nextId++,
    title: 'Request Rate (req/s)',
    type: 'timeseries',
    gridPos: { h: 8, w: 12, x: 0, y: yPos },
    targets: [{ expr: 'sum(rate(http_requests_total[5m])) by (job)', legendFormat: '{{job}}' }],
  });

  // Error rate panel
  panels.push({
    id: nextId++,
    title: 'Error Rate (%)',
    type: 'timeseries',
    gridPos: { h: 8, w: 12, x: 12, y: yPos },
    targets: [{
      expr: 'sum(rate(http_requests_total{status=~"5.."}[5m])) by (job) / sum(rate(http_requests_total[5m])) by (job) * 100',
      legendFormat: '{{job}}',
    }],
    fieldConfig: { defaults: { thresholds: { steps: [
      { value: 0, color: 'green' },
      { value: 1, color: 'yellow' },
      { value: 5, color: 'red' },
    ] } } },
  });
  yPos += 8;

  // Latency panel
  panels.push({
    id: nextId++,
    title: 'P95 Latency (ms)',
    type: 'timeseries',
    gridPos: { h: 8, w: 12, x: 0, y: yPos },
    targets: [{
      expr: 'histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (le, job)) * 1000',
      legendFormat: '{{job}}',
    }],
  });

  // Uptime panel
  panels.push({
    id: nextId++,
    title: 'Service Uptime',
    type: 'stat',
    gridPos: { h: 8, w: 12, x: 12, y: yPos },
    targets: [{ expr: 'avg(up) by (job) * 100', legendFormat: '{{job}}' }],
    fieldConfig: { defaults: { unit: 'percent', thresholds: { steps: [
      { value: 0, color: 'red' },
      { value: 99, color: 'yellow' },
      { value: 99.9, color: 'green' },
    ] } } },
  });
  yPos += 8;

  // Per-service panels
  for (const be of backends) {
    const name = slugify(be.name);
    panels.push({
      id: nextId++,
      title: `${name} — CPU & Memory`,
      type: 'timeseries',
      gridPos: { h: 8, w: 12, x: 0, y: yPos },
      targets: [
        { expr: `process_cpu_seconds_total{job="${name}"}`, legendFormat: 'CPU' },
        { expr: `process_resident_memory_bytes{job="${name}"} / 1024 / 1024`, legendFormat: 'Memory (MB)' },
      ],
    });

    panels.push({
      id: nextId++,
      title: `${name} — Request Duration`,
      type: 'timeseries',
      gridPos: { h: 8, w: 12, x: 12, y: yPos },
      targets: [
        { expr: `histogram_quantile(0.50, sum(rate(http_request_duration_seconds_bucket{job="${name}"}[5m])) by (le)) * 1000`, legendFormat: 'P50' },
        { expr: `histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{job="${name}"}[5m])) by (le)) * 1000`, legendFormat: 'P95' },
        { expr: `histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket{job="${name}"}[5m])) by (le)) * 1000`, legendFormat: 'P99' },
      ],
    });
    yPos += 8;
  }

  // Database panel (if relational)
  const dbType = doc.data.primaryDatabase.type;
  if (['postgres', 'mysql', 'sqlserver'].includes(dbType)) {
    panels.push({
      id: nextId++,
      title: 'Database Connections',
      type: 'timeseries',
      gridPos: { h: 8, w: 12, x: 0, y: yPos },
      targets: [
        { expr: 'db_pool_active_connections', legendFormat: 'Active' },
        { expr: 'db_pool_idle_connections', legendFormat: 'Idle' },
      ],
    });
    yPos += 8;
  }

  const dashboard = {
    __inputs: [],
    __requires: [],
    annotations: { list: [] },
    editable: true,
    fiscalYearStartMonth: 0,
    graphTooltip: 1,
    id: null,
    links: [],
    panels,
    schemaVersion: 39,
    tags: ['arch0', slugify(doc.solution.name)],
    templating: { list: [] },
    time: { from: 'now-1h', to: 'now' },
    timepicker: {},
    timezone: 'browser',
    title: `${doc.solution.name} — Overview`,
    uid: slugify(doc.solution.name) + '-overview',
    version: 1,
  };

  return JSON.stringify(dashboard, null, 2) + '\n';
}
