import type { SDLDocument } from '../types';
import type { RawGeneratorResult, GeneratedFile } from './types';

/**
 * Generates Nginx reverse proxy configuration.
 * Routes frontends and backend APIs through a single entry point.
 * Includes SSL placeholder, gzip compression, and proxy headers.
 * Deterministic — same input always produces identical output.
 */
export function generateNginxConfig(doc: SDLDocument): RawGeneratorResult {
  const files: GeneratedFile[] = [];
  const frontends = doc.architecture.projects.frontend || [];
  const backends = doc.architecture.projects.backend || [];

  files.push({
    path: 'artifacts/nginx/nginx.conf',
    content: renderNginxConf(doc, frontends, backends),
  });

  files.push({
    path: 'artifacts/nginx/mime.types.conf',
    content: renderMimeTypes(),
  });

  // Docker Compose snippet for nginx service
  files.push({
    path: 'artifacts/nginx/docker-compose.nginx.yml',
    content: renderNginxCompose(doc, backends),
  });

  return {
    artifactType: 'deployment-guide',
    files,
    metadata: {
      solutionName: doc.solution.name,
      backendUpstreams: backends.length,
      frontendUpstreams: frontends.length,
      hasSslPlaceholder: true,
      hasGzip: true,
      hasRateLimiting: true,
    },
  };
}

// ─── Helpers ───

function slugify(s: string): string {
  return s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
}

function getBackendPort(framework: string): number {
  switch (framework) {
    case 'python-fastapi': return 8000;
    case 'go': return 8080;
    case 'dotnet-8': return 5000;
    case 'java-spring': return 8080;
    case 'ruby-rails': return 3000;
    case 'php-laravel': return 9000;
    default: return 3000;
  }
}

// ─── Renderers ───

function renderNginxConf(
  doc: SDLDocument,
  frontends: { name: string; framework: string }[],
  backends: { name: string; framework: string }[],
): string {
  const lines: string[] = [];
  const host = doc.solution.domain || `${slugify(doc.solution.name)}.example.com`;

  lines.push(`# Nginx reverse proxy — ${doc.solution.name}`);
  lines.push('# Generated by arch0 SDL');
  lines.push('');
  lines.push('worker_processes auto;');
  lines.push('error_log /var/log/nginx/error.log warn;');
  lines.push('pid /var/run/nginx.pid;');
  lines.push('');
  lines.push('events {');
  lines.push('    worker_connections 1024;');
  lines.push('}');
  lines.push('');
  lines.push('http {');
  lines.push('    include /etc/nginx/mime.types;');
  lines.push('    default_type application/octet-stream;');
  lines.push('');

  // Logging
  lines.push('    log_format main \'$remote_addr - $remote_user [$time_local] "$request" \'');
  lines.push('                    \'$status $body_bytes_sent "$http_referer" \'');
  lines.push('                    \'"$http_user_agent" "$http_x_forwarded_for"\';');
  lines.push('    access_log /var/log/nginx/access.log main;');
  lines.push('');

  // Performance
  lines.push('    sendfile on;');
  lines.push('    tcp_nopush on;');
  lines.push('    tcp_nodelay on;');
  lines.push('    keepalive_timeout 65;');
  lines.push('    types_hash_max_size 2048;');
  lines.push('    client_max_body_size 10m;');
  lines.push('');

  // Gzip
  lines.push('    # Gzip compression');
  lines.push('    gzip on;');
  lines.push('    gzip_vary on;');
  lines.push('    gzip_proxied any;');
  lines.push('    gzip_comp_level 6;');
  lines.push('    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript image/svg+xml;');
  lines.push('');

  // Rate limiting zone
  lines.push('    # Rate limiting');
  lines.push('    limit_req_zone $binary_remote_addr zone=api:10m rate=30r/s;');
  lines.push('');

  // Upstream blocks for backends
  for (const be of backends) {
    const name = slugify(be.name);
    const port = getBackendPort(be.framework);
    lines.push(`    # Backend: ${be.name} (${be.framework})`);
    lines.push(`    upstream ${name} {`);
    lines.push(`        server ${name}:${port};`);
    lines.push('    }');
    lines.push('');
  }

  // Upstream blocks for frontends
  for (const fe of frontends) {
    const name = slugify(fe.name);
    lines.push(`    # Frontend: ${fe.name} (${fe.framework})`);
    lines.push(`    upstream ${name} {`);
    lines.push(`        server ${name}:80;`);
    lines.push('    }');
    lines.push('');
  }

  // HTTP redirect to HTTPS
  lines.push('    # Redirect HTTP to HTTPS');
  lines.push('    server {');
  lines.push('        listen 80;');
  lines.push(`        server_name ${host};`);
  lines.push('        return 301 https://$server_name$request_uri;');
  lines.push('    }');
  lines.push('');

  // HTTPS server
  lines.push('    # HTTPS server');
  lines.push('    server {');
  lines.push('        listen 443 ssl http2;');
  lines.push(`        server_name ${host};`);
  lines.push('');
  lines.push('        # SSL certificates (replace with your paths)');
  lines.push(`        ssl_certificate /etc/nginx/ssl/${host}.crt;`);
  lines.push(`        ssl_certificate_key /etc/nginx/ssl/${host}.key;`);
  lines.push('');
  lines.push('        # SSL settings');
  lines.push('        ssl_protocols TLSv1.2 TLSv1.3;');
  lines.push('        ssl_ciphers HIGH:!aNULL:!MD5;');
  lines.push('        ssl_prefer_server_ciphers on;');
  lines.push('        ssl_session_cache shared:SSL:10m;');
  lines.push('        ssl_session_timeout 10m;');
  lines.push('');

  // Security headers
  lines.push('        # Security headers');
  lines.push('        add_header X-Frame-Options "SAMEORIGIN" always;');
  lines.push('        add_header X-Content-Type-Options "nosniff" always;');
  lines.push('        add_header X-XSS-Protection "1; mode=block" always;');
  lines.push('        add_header Referrer-Policy "strict-origin-when-cross-origin" always;');
  lines.push('');

  // Backend API locations
  for (const be of backends) {
    const name = slugify(be.name);
    const prefix = backends.length === 1 ? '/api' : `/api/${name}`;
    lines.push(`        # API: ${be.name}`);
    lines.push(`        location ${prefix} {`);
    lines.push('            limit_req zone=api burst=50 nodelay;');
    lines.push('');
    lines.push(`            proxy_pass http://${name};`);
    lines.push('            proxy_http_version 1.1;');
    lines.push('            proxy_set_header Host $host;');
    lines.push('            proxy_set_header X-Real-IP $remote_addr;');
    lines.push('            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;');
    lines.push('            proxy_set_header X-Forwarded-Proto $scheme;');
    lines.push('            proxy_set_header X-Request-ID $request_id;');
    lines.push('');
    lines.push('            # WebSocket support');
    lines.push('            proxy_set_header Upgrade $http_upgrade;');
    lines.push('            proxy_set_header Connection "upgrade";');
    lines.push('');
    lines.push('            proxy_connect_timeout 60s;');
    lines.push('            proxy_send_timeout 60s;');
    lines.push('            proxy_read_timeout 60s;');
    lines.push('        }');
    lines.push('');
  }

  // Health check endpoint
  lines.push('        # Health check');
  lines.push('        location /health {');
  lines.push('            access_log off;');
  lines.push('            return 200 "ok";');
  lines.push('        }');
  lines.push('');

  // Frontend location (first frontend as default)
  if (frontends.length > 0) {
    const feName = slugify(frontends[0].name);
    lines.push('        # Frontend');
    lines.push('        location / {');
    lines.push(`            proxy_pass http://${feName};`);
    lines.push('            proxy_http_version 1.1;');
    lines.push('            proxy_set_header Host $host;');
    lines.push('            proxy_set_header X-Real-IP $remote_addr;');
    lines.push('            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;');
    lines.push('            proxy_set_header X-Forwarded-Proto $scheme;');
    lines.push('        }');
  } else {
    lines.push('        # No frontend — serve 404');
    lines.push('        location / {');
    lines.push('            return 404;');
    lines.push('        }');
  }

  lines.push('    }');
  lines.push('}');

  return lines.join('\n') + '\n';
}

function renderMimeTypes(): string {
  return `# Common MIME types for static assets
types {
    text/html                             html htm;
    text/css                              css;
    text/javascript                       js mjs;
    application/json                      json;
    application/xml                       xml;
    image/png                             png;
    image/jpeg                            jpg jpeg;
    image/gif                             gif;
    image/svg+xml                         svg svgz;
    image/webp                            webp;
    font/woff                             woff;
    font/woff2                            woff2;
    application/font-woff                 woff;
    application/font-woff2                woff2;
    application/vnd.ms-fontobject         eot;
    font/ttf                              ttf;
    font/otf                              otf;
    application/wasm                      wasm;
    video/mp4                             mp4;
    audio/mpeg                            mp3;
    application/pdf                       pdf;
    application/zip                       zip;
}
`;
}

function renderNginxCompose(
  doc: SDLDocument,
  backends: { name: string; framework: string }[],
): string {
  const lines: string[] = [];
  const name = slugify(doc.solution.name);

  lines.push(`# Nginx service for docker-compose — ${doc.solution.name}`);
  lines.push('# Add this to your docker-compose.yml services section');
  lines.push('');
  lines.push('services:');
  lines.push('  nginx:');
  lines.push('    image: nginx:alpine');
  lines.push(`    container_name: ${name}-nginx`);
  lines.push('    ports:');
  lines.push('      - "80:80"');
  lines.push('      - "443:443"');
  lines.push('    volumes:');
  lines.push('      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro');
  lines.push('      - ./nginx/ssl:/etc/nginx/ssl:ro');
  lines.push('    depends_on:');
  for (const be of backends) {
    lines.push(`      - ${slugify(be.name)}`);
  }
  lines.push('    restart: unless-stopped');

  return lines.join('\n') + '\n';
}
